[tool.poetry]
name = "cohere"
version = "4.3.1"
description = ""
authors = ["Cohere"]
readme = "README.md"

[tool.black]
line-length = 120
target_version = ['py38']
include = '\.py$'

[tool.isort]
profile = "black"
skip_glob = '^((?!py$).)*$' # python files

[tool.poetry.dependencies]
python = "^3.7, <4.0"
requests = "^2.0"
aiohttp = "^3.0"
backoff = "^2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-asyncio = "^0.20.2"
black = "^22.10.0"
isort = "^5.10.1"
pre-commit = "^2.20.0"
autoflake = "^1.7.8"
Sphinx = "^5.0"
sphinx-rtd-theme = "^1.2.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.core.masonry.api"
