name: sync-internal

on: 
  push:
    branches:
      - main
      - sync-internal

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://cohere-ci:${{ secrets.GH_PAT }}@github.com/cohere-ai/cohere-python.git"
          source_branch: "main"
          destination_repo: "https://cohere-ci:${{ secrets.GH_PAT }}@github.com/cohere-ai/cohere-python-internal.git"
          destination_branch: "main"
      - uses: actions/checkout@v3
        with:
          repository: cohere-ai/cohere-python-internal
          ref: main
          token: ${{ secrets.GH_PAT }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: remove README and github actions
        run: |
          rm -rf .github/ README.md
          git fetch origin overrides:overrides 
          git checkout overrides -- .github/ README.md
          git add .
          git commit -m "Apply README and Github Actions"
      - run: git push origin main

